import { useEffect } from 'react';
import ReactMarkdown from 'react-markdown';
import type { Summary } from '../../shared/types';
import { useFeeds } from '../hooks/useFeeds';
import { useSummary } from '../hooks/useSummary';
import ProgressIndicator from './ProgressIndicator';
import './SummaryView.css';

function slugify(input: string): string {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80) || 'summary';
}

function downloadSummaryMarkdown(title: string, summary: Summary) {
  const generated = new Date(summary.createdAt).toISOString();
  const frontmatter = [
    '---',
    `title: ${JSON.stringify(title)}`,
    `provider: ${summary.provider}`,
    `model: ${summary.model}`,
    `generated: ${generated}`,
    '---',
    '',
  ].join('\n');
  const content = `${frontmatter}# ${title}\n\n${summary.markdown}\n`;
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${slugify(title)}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// Fix #9: Strip dangerous URI schemes from markdown links
function sanitizeLinkUri(uri: string): string {
  const trimmed = uri.trim().toLowerCase();
  if (
    trimmed.startsWith('javascript:') ||
    trimmed.startsWith('vbscript:') ||
    (trimmed.startsWith('data:') && !trimmed.startsWith('data:image'))
  ) {
    return '';
  }
  return uri;
}

export default function SummaryView() {
  const { selectedEpisodeId, episodes, refreshStatuses } = useFeeds();
  const episode = episodes.find(e => e.guid === selectedEpisodeId) || null;
  const {
    stage,
    error,
    transcript,
    summary,
    loadCached,
    runPipeline,
    runTranscription,
    runSummarisation,
  } = useSummary(selectedEpisodeId, episode?.audioUrl || null, refreshStatuses);

  useEffect(() => {
    loadCached();
  }, [loadCached]);

  const isYouTube = episode?.guid?.startsWith('yt:') ?? false;

  if (!selectedEpisodeId) {
    return (
      <div className="summary-view">
        <div className="summary-view-header">Summary</div>
        <div className="summary-view-body">
          <p className="no-selection">Select an episode to view or generate a summary.</p>
        </div>
      </div>
    );
  }

  return (
    <div className="summary-view">
      <div className="summary-view-header">Summary</div>
      <div className="summary-view-body">
        <h2>{episode?.title}</h2>

        {episode?.description && (
          <details className="episode-description-details" open={!summary}>
            <summary>Episode Description</summary>
            <p className="episode-description">{episode.description}</p>
          </details>
        )}

        <div className="episode-actions" style={{ margin: '12px 0' }}>
          {!summary && (
            <button onClick={runPipeline} disabled={stage !== 'idle'}>
              {transcript ? 'Summarise' : 'Transcribe & Summarise'}
            </button>
          )}
          {transcript && !summary && (
            <button onClick={() => runSummarisation()} disabled={stage !== 'idle'} style={{ marginLeft: 8 }}>
              Summarise Only
            </button>
          )}
          {!transcript && (
            <button onClick={runTranscription} disabled={stage !== 'idle'} style={{ marginLeft: 8 }}>
              {isYouTube ? 'Get Transcript' : 'Transcribe Only'}
            </button>
          )}
          {summary && (
            <button onClick={() => runSummarisation(transcript?.text)} disabled={stage !== 'idle'} style={{ marginLeft: 8 }}>
              Re-summarise
            </button>
          )}
          {summary && (
            <button
              onClick={() => downloadSummaryMarkdown(episode?.title || 'summary', summary)}
              style={{ marginLeft: 8 }}
            >
              Download Markdown
            </button>
          )}
        </div>

        {stage === 'transcribing' && <ProgressIndicator message={isYouTube ? "Fetching transcript..." : "Transcribing audio... this may take a few minutes."} />}
        {stage === 'summarising' && <ProgressIndicator message="Generating summary..." />}
        {error && <div className="error-msg">{error}</div>}

        {summary && (
          <div className="summary-content">
            <ReactMarkdown urlTransform={sanitizeLinkUri}>{summary.markdown}</ReactMarkdown>
            <p style={{ fontSize: '0.75rem', color: '#999', marginTop: 16 }}>
              Generated by {summary.provider} ({summary.model}) on{' '}
              {new Date(summary.createdAt).toLocaleString()}
            </p>
          </div>
        )}

        {transcript && !summary && (
          <details style={{ marginTop: 12 }}>
            <summary style={{ cursor: 'pointer', fontSize: '0.85rem' }}>View transcript</summary>
            <pre style={{ whiteSpace: 'pre-wrap', fontSize: '0.8rem', marginTop: 8, maxHeight: 400, overflow: 'auto' }}>
              {transcript.text}
            </pre>
          </details>
        )}
      </div>
    </div>
  );
}
